import { build } from 'esbuild';
import { rmSync, mkdirSync } from 'node:fs';

rmSync('dist', { recursive: true, force: true });
mkdirSync('dist', { recursive: true });

// Three entry points. The hook is bundled without the Jev client in its
// eager path; esbuild keeps the dynamic import() split so on-demand mode
// never parses SDK code.
await build({
  entryPoints: ['src/hook.ts', 'src/cli.ts', 'src/eval.ts', 'src/redact.ts'],
  outdir: 'dist',
  bundle: true,
  splitting: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: { js: '// JevPromptCoach — generated by scripts/build.mjs. Do not edit.' },
});

console.log('built dist/');
